
package com.itheima.soft.biz.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoftctrServiceService", targetNamespace = "http://impl.biz.soft.itheima.com/", wsdlLocation = "http://localhost:8080/soft_web/ws/softctr?wsdl")
public class SoftctrServiceService
    extends Service
{

    private final static URL SOFTCTRSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SOFTCTRSERVICESERVICE_EXCEPTION;
    private final static QName SOFTCTRSERVICESERVICE_QNAME = new QName("http://impl.biz.soft.itheima.com/", "SoftctrServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/soft_web/ws/softctr?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOFTCTRSERVICESERVICE_WSDL_LOCATION = url;
        SOFTCTRSERVICESERVICE_EXCEPTION = e;
    }

    public SoftctrServiceService() {
        super(__getWsdlLocation(), SOFTCTRSERVICESERVICE_QNAME);
    }

    public SoftctrServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOFTCTRSERVICESERVICE_QNAME, features);
    }

    public SoftctrServiceService(URL wsdlLocation) {
        super(wsdlLocation, SOFTCTRSERVICESERVICE_QNAME);
    }

    public SoftctrServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOFTCTRSERVICESERVICE_QNAME, features);
    }

    public SoftctrServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoftctrServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ISoftctrService
     */
    @WebEndpoint(name = "SoftctrServicePort")
    public ISoftctrService getSoftctrServicePort() {
        return super.getPort(new QName("http://impl.biz.soft.itheima.com/", "SoftctrServicePort"), ISoftctrService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISoftctrService
     */
    @WebEndpoint(name = "SoftctrServicePort")
    public ISoftctrService getSoftctrServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.biz.soft.itheima.com/", "SoftctrServicePort"), ISoftctrService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOFTCTRSERVICESERVICE_EXCEPTION!= null) {
            throw SOFTCTRSERVICESERVICE_EXCEPTION;
        }
        return SOFTCTRSERVICESERVICE_WSDL_LOCATION;
    }

}
