
package com.itheima.soft.biz.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.itheima.soft.biz.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ISoftctrService", targetNamespace = "http://biz.soft.itheima.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ISoftctrService {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doLogin", targetNamespace = "http://biz.soft.itheima.com/", className = "com.itheima.soft.biz.DoLogin")
    @ResponseWrapper(localName = "doLoginResponse", targetNamespace = "http://biz.soft.itheima.com/", className = "com.itheima.soft.biz.DoLoginResponse")
    public String doLogin(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

}
